name: Notify issue creation
on:
  issues:
    types:
      - opened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New blog: ${{ github.event.issue.title }}
            ${{ github.event.issue.body }}
            Link: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}
